# Generated by Django 2.1.5 on 2020-06-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200607_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplatters',
            name='upsize',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='upsize',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='sub',
            name='upsize',
            field=models.CharField(max_length=5),
        ),
    ]
