# Generated by Django 2.1.5 on 2020-06-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200607_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplatters',
            old_name='upsize',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='upsize',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='upsize',
            new_name='size',
        ),
    ]
