# Generated by Django 2.1.5 on 2020-06-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200607_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplatters',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='dinnerplatters',
            old_name='size',
            new_name='Size',
        ),
        migrations.RenameField(
            model_name='dinnerplatters',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='pasta',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='pasta',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='pizzaDetails',
            new_name='Details',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='size',
            new_name='Size',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='salads',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='salads',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='size',
            new_name='Size',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='toppings',
            old_name='type',
            new_name='Type',
        ),
    ]
