# Generated by Django 2.1.5 on 2020-06-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200609_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_addition',
            name='Size',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
