# Generated by Django 2.1.5 on 2020-06-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplatters',
            name='Category',
            field=models.CharField(default='Dinner Platters', max_length=15),
        ),
        migrations.AddField(
            model_name='pasta',
            name='Category',
            field=models.CharField(default='Pasta', max_length=5),
        ),
        migrations.AddField(
            model_name='pizza',
            name='Category',
            field=models.CharField(default='Pizza', max_length=5),
        ),
        migrations.AddField(
            model_name='salads',
            name='Category',
            field=models.CharField(default='Salads', max_length=6),
        ),
        migrations.AddField(
            model_name='sub',
            name='Category',
            field=models.CharField(default='Sub', max_length=3),
        ),
    ]
