# Generated by Django 2.1.5 on 2020-06-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='Completed',
        ),
        migrations.AddField(
            model_name='order',
            name='Submited',
            field=models.BooleanField(default=False),
        ),
    ]
