# Generated by Django 2.1.5 on 2020-06-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200611_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Submited',
            new_name='Submitted',
        ),
    ]
